

services:
  pygeoapi:
    build: .
    # image: pygeo-opentel:latest

    container_name: pygeoapi_otel

    ports:
      - 5000:80

    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./data:/data
      - ./plugins/process/squared.py:/pygeoapi/pygeoapi/process/squared.py
      - ./plugins/process/localoutlier.py:/pygeoapi/pygeoapi/process/localoutlier.py
      - ./plugins/process/localoutlier_simple.py:/pygeoapi/pygeoapi/process/localoutlier_simple.py


  collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - 4318:4318
          
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

networks:
  default:
    name: pygeoapi_otel
    driver: bridge